"""
Synthetic Data Generator — Issue #119
Tables: request_comments, volunteer_rating
Schema source: database/mock-data-generation/db_info.json

Usage (with external CSVs from other team — preferred for full FK integrity):
    python generate_119.py --users-csv database/mock_db/users.csv \
                           --requests-csv database/mock_db/request.csv

    When external CSVs are provided, user_id and req_id values are read
    directly from those files — guaranteeing referential integrity across
    ALL synthetic tables generated by ALL teams.

Output:
    database/mock_db/request_comments.csv
    database/mock_db/volunteer_rating.csv
"""

import csv
import random
import uuid
import argparse
from datetime import datetime, timedelta
from pathlib import Path


RANDOM_SEED = 42
random.seed(RANDOM_SEED)

OUTPUT_DIR = Path("database/mock_db")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

START_DATE = datetime(2024, 1, 1)
END_DATE   = datetime(2026, 3, 1)


# Source: test-saayam.netlify.app category dropdown
# Matches exactly what is stored in help_categories table

CATEGORY_TREE = {
    "Clothing Assistance": [
        "Donate Clothes",
        "Borrow Clothes",
        "Emergency Clothing Assistance",
        "Tailoring",
    ],
    "Education & Career Support": [
        "College Application Help",
        "SOP & Essay Review",
        "Tutoring - Math",
        "Tutoring - English",
        "Tutoring - Science",
        "Tutoring - Computer Science",
        "Tutoring - Test Prep",
        "Tutoring - Other Subjects",
        "Scholarship Knowledge",
        "Study Group Formation",
        "Career Guidance",
        "Education Resource Sharing",
    ],
    "Elderly Community Assistance": [
        "Senior Relocation Support",
        "Digital Support for Seniors",
        "Medication Management",
        "Medical Devices Setup",
        "Errands, Events & Transportation",
        "Transportation for Appointments",
        "Scheduling Appointments or Tasks",
        "Social Connection",
        "Meal Support",
    ],
    "Food & Essentials": [
        "Food Assistance",
        "Grocery Shopping & Delivery",
        "Cooking Help - Meal Prep Basic",
        "Cooking Help - Festive or Bulk Cooking",
        "Cooking Help - Nutritional Meal Planning",
        "Cooking Help - Cultural Cuisine Guidance",
        "Cooking Help - Other",
    ],
    "Healthcare & Wellness": [
        "Medical Consultation - General",
        "Medical Consultation - ENT",
        "Medical Consultation - Dental / Oral Health",
        "Medical Consultation - Eye / Vision Care",
        "Medical Consultation - Cardiac / Blood Pressure",
        "Medical Consultation - Orthopedic / Physiotherapy",
        "Medical Consultation - Skin / Dermatology",
        "Medical Consultation - Women's / Reproductive Health",
        "Medical Consultation - Vaccinations & Preventive Screenings",
        "Medical Consultation - Pediatrics / Child Health",
        "Medical Consultation - Other",
        "Medicine Delivery",
        "Mental Wellbeing Support",
        "Medication Reminders",
        "Health Education Guidance",
    ],
    "Housing Assistance": [
        "Lease Support",
        "Tenant Rent Support",
        "Repair & Maintenance - Plumbing",
        "Repair & Maintenance - Handyman",
        "Repair & Maintenance - Electrician",
        "Repair & Maintenance - Carpentry",
        "Repair & Maintenance - Gardening",
        "Repair & Maintenance - HVAC / Air Conditioning",
        "Repair & Maintenance - Roofing",
        "Repair & Maintenance - Locksmith",
        "Repair & Maintenance - Painting",
        "Repair & Maintenance - Masonry / Concrete",
        "Repair & Maintenance - Metalwork / Welding",
        "Repair & Maintenance - Pool & Spa Maintenance",
        "Repair & Maintenance - Other",
        "Utilities Setup Support",
        "Looking for Rental",
        "Find a Roommate",
        "Move-in Help",
        "Packers & Movers Support",
        "Buy Household Items",
        "Sell Household Items",
    ],
    "General": [
        "General",
    ],
}

# Flat list of all parent categories for distribution weighting
# Weighted to reflect real usage — Food/Healthcare/Education most common
PARENT_CATEGORIES = list(CATEGORY_TREE.keys())
PARENT_WEIGHTS    = [0.08, 0.18, 0.10, 0.22, 0.20, 0.17, 0.05]

def random_category():
    """Pick a realistic parent + subcategory pair."""
    parent = random.choices(PARENT_CATEGORIES, weights=PARENT_WEIGHTS, k=1)[0]
    sub    = random.choice(CATEGORY_TREE[parent])
    return parent, sub


# REALISTIC COMMENT TEXT — mapped to real categories
COMMENT_TEMPLATES = {
    "Clothing Assistance": [
        "I have some clothing items to donate — can connect offline.",
        "Happy to help with tailoring. I have a sewing machine at home.",
        "Emergency clothing need noted. Connecting with local shelter.",
        "Following up — did you receive the donated items?",
    ],
    "Education & Career Support": [
        "I can help with math tutoring on weekends. Available via Zoom.",
        "I reviewed the SOP draft — sent feedback via email.",
        "College application process can be overwhelming. Happy to guide step by step.",
        "Connecting you with a scholarship database for your field.",
        "Career guidance session scheduled for next Tuesday.",
        "Study group formed — 4 members, meeting every Sunday.",
    ],
    "Elderly Community Assistance": [
        "Transportation to the appointment is arranged for Thursday.",
        "Helped set up video calling on the tablet. All good now.",
        "Medication schedule has been organized into a weekly pill box.",
        "Grocery run completed. Dropped off at the door.",
        "Social visit done — had a great conversation. Will follow up next week.",
    ],
    "Food & Essentials": [
        "Grocery delivery arranged for tomorrow morning.",
        "Connected with the local food bank — pickup available Tuesday.",
        "Meal prep completed for the week. Dropped off containers.",
        "Food assistance processed. Waiting for confirmation of receipt.",
        "Nutritional meal plan shared via WhatsApp.",
        "Still waiting for a volunteer in the Detroit area. Escalating.",
    ],
    "Healthcare & Wellness": [
        "General consultation arranged with a volunteer doctor via telemedicine.",
        "Medication delivery confirmed for tomorrow.",
        "Mental wellbeing session completed. Person is doing better.",
        "Dental referral provided — contact shared.",
        "Medication reminder schedule set up on their phone.",
        "Following up — please confirm if the health issue has been resolved.",
        "Connected with a physiotherapy volunteer in the area.",
    ],
    "Housing Assistance": [
        "Plumber has been contacted. Appointment scheduled for Saturday.",
        "Lease support provided — reviewed the contract and flagged key clauses.",
        "Move-in help coordinated — 3 volunteers available next weekend.",
        "Electrician visited and resolved the issue. Marking resolved.",
        "Rental listings shared for the requested area and budget.",
        "Roommate connection made — please follow up directly.",
        "HVAC technician availability confirmed for Friday afternoon.",
    ],
    "General": [
        "Request received. Reviewing and will follow up shortly.",
        "More details needed to find the right volunteer. Please update.",
        "This has been resolved. Closing the request.",
        "Escalating to the team for faster resolution.",
        "Following up — is additional support still needed?",
    ],
}

def pick_comment(parent_category: str, subcategory: str) -> str:
    """Pick realistic comment text for a given category."""
    templates = COMMENT_TEMPLATES.get(parent_category,
                                      COMMENT_TEMPLATES["General"])
    base = random.choice(templates)
    # Occasionally add subcategory context
    if random.random() < 0.3 and subcategory != "General":
        base += f" (Re: {subcategory})"
    return base


# FEEDBACK TEXT — matches rating sentiment

FEEDBACK = {
    5: [
        "The volunteer was incredibly helpful and kind. Made a real difference.",
        "Showed up on time and went above and beyond expectations.",
        "Outstanding support. Very professional and understanding throughout.",
        "Fast response, genuine care. Could not have asked for better help.",
        "The help I received changed my situation significantly. Thank you.",
        "Knowledgeable, compassionate, and efficient. Highly recommend.",
        "Wonderful experience — the volunteer truly understood my situation.",
    ],
    4: [
        "Very helpful overall. Minor delay but the quality of support was great.",
        "Good experience. The volunteer was thorough and communicative.",
        "Appreciated the support — would have liked slightly faster response.",
        "Solid help. The volunteer went the extra mile in most areas.",
        "Great follow-through. A small miscommunication early on but resolved well.",
    ],
    3: [
        "Decent help but took longer than expected to get started.",
        "The volunteer was helpful but communication could be improved.",
        "Got the help I needed eventually. Average experience overall.",
        "Good intentions but the coordination could use improvement.",
        "Satisfactory. The volunteer did their best with limited resources.",
    ],
    2: [
        "Poor communication. Had to follow up multiple times.",
        "The help provided did not fully match what was needed.",
        "Felt rushed. Did not take enough time to understand the situation.",
        "Volunteer was late and did not complete the task as agreed.",
    ],
    1: [
        "The volunteer did not show up as scheduled. Very disappointing.",
        "No follow-up after initial contact. Left me in a difficult spot.",
        "The help provided was inadequate for my situation.",
        "Volunteer was unresponsive after being assigned. Frustrating experience.",
    ],
}

RATING_WEIGHTS = [0.04, 0.06, 0.12, 0.33, 0.45]


# LOCATION POOL — US cities realistic for as per saayam app

LOCATIONS = [
    "Tampa, FL", "Chicago, IL", "New York, NY", "Houston, TX",
    "Phoenix, AZ", "Philadelphia, PA", "San Antonio, TX",
    "San Diego, CA", "Dallas, TX", "San Jose, CA",
    "Austin, TX", "Jacksonville, FL", "Detroit, MI",
    "Columbus, OH", "Memphis, TN", "Atlanta, GA",
    "Seattle, WA", "Denver, CO", "Boston, MA", "Miami, FL",
    "Portland, OR", "Las Vegas, NV", "Minneapolis, MN", "Charlotte, NC",
]


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def random_timestamp(start: datetime, end: datetime) -> str:
    if start >= end:
        return start.strftime("%Y-%m-%d %H:%M:%S")
    delta = end - start
    random_seconds = random.randint(0, int(delta.total_seconds()))
    return (start + timedelta(seconds=random_seconds)).strftime("%Y-%m-%d %H:%M:%S")


def make_user_id() -> str:
    return f"cognito_{uuid.UUID(int=random.getrandbits(128), version=4)}"


def make_request_id() -> str:
    return f"REQ-{str(uuid.UUID(int=random.getrandbits(128), version=4))[:8].upper()}"


# ─────────────────────────────────────────────
# LOAD EXTERNAL CSVs (when provided by other team)
# ─────────────────────────────────────────────

def load_external_users(filepath: str) -> list:
    """
    Load user_ids from the users.csv generated by another team.
    Expects a CSV with at minimum a 'user_id' column.
    """
    users = []
    with open(filepath, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            users.append({"user_id": row["user_id"]})
    print(f"  Loaded {len(users):,} users from {filepath}")
    return users


def load_external_requests(filepath: str) -> list:
    """
    Load request data from request.csv generated by another team.
    Expects columns: req_id, req_cat_id (or req_cat), req_loc, created_at (or req_created_at)
    Column names are flexible — we try common variants.
    """
    requests = []
    with open(filepath, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        cols = reader.fieldnames or []

        # Detect column name variants
        id_col  = next((c for c in cols if 'req_id' in c.lower()), None)
        cat_col = next((c for c in cols if 'cat' in c.lower()), None)
        loc_col = next((c for c in cols if 'loc' in c.lower()), None)
        dt_col  = next((c for c in cols if 'creat' in c.lower() or 'date' in c.lower()), None)

        for row in reader:
            # Parse created_at — fall back to a random date if missing/malformed
            raw_dt = row.get(dt_col, "") if dt_col else ""
            try:
                created_at = datetime.strptime(raw_dt[:19], "%Y-%m-%d %H:%M:%S")
            except Exception:
                created_at = START_DATE + timedelta(
                    days=random.randint(0, (END_DATE - START_DATE).days)
                )

            # Map category to our parent hierarchy
            raw_cat = row.get(cat_col, "General") if cat_col else "General"
            parent  = map_category_to_parent(raw_cat)
            sub     = raw_cat if raw_cat in [s for subs in CATEGORY_TREE.values()
                                              for s in subs] else parent

            requests.append({
                "req_id":    row.get(id_col, make_request_id()) if id_col else make_request_id(),
                "category":  parent,
                "subcategory": sub,
                "location":  row.get(loc_col, random.choice(LOCATIONS)) if loc_col else random.choice(LOCATIONS),
                "created_at": created_at.strftime("%Y-%m-%d %H:%M:%S"),
            })

    print(f"  Loaded {len(requests):,} requests from {filepath}")
    return requests


def map_category_to_parent(raw: str) -> str:
    """Map a raw category string to one of our 7 parent categories."""
    raw_lower = raw.lower()
    mapping = {
        "food":      "Food & Essentials",
        "grocery":   "Food & Essentials",
        "meal":      "Food & Essentials",
        "cook":      "Food & Essentials",
        "health":    "Healthcare & Wellness",
        "medical":   "Healthcare & Wellness",
        "medicine":  "Healthcare & Wellness",
        "mental":    "Healthcare & Wellness",
        "wellness":  "Healthcare & Wellness",
        "housing":   "Housing Assistance",
        "repair":    "Housing Assistance",
        "rent":      "Housing Assistance",
        "lease":     "Housing Assistance",
        "move":      "Housing Assistance",
        "shelter":   "Housing Assistance",
        "education": "Education & Career Support",
        "tutor":     "Education & Career Support",
        "career":    "Education & Career Support",
        "college":   "Education & Career Support",
        "school":    "Education & Career Support",
        "elderly":   "Elderly Community Assistance",
        "senior":    "Elderly Community Assistance",
        "clothing":  "Clothing Assistance",
        "clothes":   "Clothing Assistance",
        "tailor":    "Clothing Assistance",
    }
    for keyword, parent in mapping.items():
        if keyword in raw_lower:
            return parent
    return "General"


# ─────────────────────────────────────────────
# BUILD INTERNAL POOL (when no external CSVs)
# ─────────────────────────────────────────────

def build_reference_pool(n_users: int, n_requests: int) -> tuple:
    """Generate internal user/request pools when external CSVs not provided."""
    users = [{"user_id": make_user_id()} for _ in range(n_users)]

    requests = []
    for _ in range(n_requests):
        parent, sub  = random_category()
        created_at   = random_timestamp(START_DATE, END_DATE)
        requests.append({
            "req_id":      make_request_id(),
            "category":    parent,
            "subcategory": sub,
            "location":    random.choice(LOCATIONS),
            "created_at":  created_at,
        })

    return users, requests


# ─────────────────────────────────────────────
# TABLE 1: request_comments
# ─────────────────────────────────────────────

def generate_request_comments(users: list, requests: list, n_rows: int) -> list:
    """
    Generate synthetic request_comments rows.
    comment_desc uses real Saayam category-specific language.
    """
    rows = []
    for comment_id in range(1, n_rows + 1):
        req = random.choice(requests)

        # 25% chance the commenter is the requester (follow-up)
        # 75% chance it's a volunteer (different user)
        if random.random() < 0.25:
            req_user = next((u for u in users
                             if u["user_id"] == req.get("req_user_id", "")),
                            random.choice(users))
            commenter = req_user
        else:
            commenter = random.choice(users)

        req_dt        = datetime.strptime(req["created_at"], "%Y-%m-%d %H:%M:%S")
        comment_start = req_dt
        comment_end   = min(req_dt + timedelta(days=30), END_DATE)
        created_at    = random_timestamp(comment_start, comment_end)

        created_dt   = datetime.strptime(created_at, "%Y-%m-%d %H:%M:%S")
        updated_end  = min(created_dt + timedelta(hours=72), END_DATE)
        last_updated = random_timestamp(created_dt, updated_end)

        comment_desc = pick_comment(
            req.get("category", "General"),
            req.get("subcategory", "General")
        )

        rows.append({
            "comment_id":      comment_id,
            "req_id":          req["req_id"],
            "commenter_id":    commenter["user_id"],
            "comment_desc":    comment_desc,
            "created_at":      created_at,
            "last_updated_at": last_updated,
            "isdeleted":       "TRUE" if random.random() < 0.05 else "FALSE",
        })

    return rows


# ─────────────────────────────────────────────
# TABLE 2: volunteer_rating
# ─────────────────────────────────────────────

def generate_volunteer_rating(users: list, requests: list, n_rows: int) -> list:
    """
    Generate synthetic volunteer_rating rows.
    Rating distribution is realistic (skewed positive).
    Feedback text matches rating sentiment.
    One unique (user_id, request_id) pair per row — no duplicates.
    """
    rows       = []
    seen_pairs = set()
    rating_id  = 1
    attempts   = 0
    max_att    = n_rows * 10

    while len(rows) < n_rows and attempts < max_att:
        attempts += 1
        req  = random.choice(requests)
        user = random.choice(users)
        pair = (user["user_id"], req["req_id"])
        if pair in seen_pairs:
            continue
        seen_pairs.add(pair)

        rating   = random.choices([1, 2, 3, 4, 5], weights=RATING_WEIGHTS, k=1)[0]
        feedback = random.choice(FEEDBACK[rating])

        req_dt       = datetime.strptime(req["created_at"], "%Y-%m-%d %H:%M:%S")
        rating_start = req_dt + timedelta(hours=1)
        rating_end   = min(req_dt + timedelta(days=14), END_DATE)
        if rating_start >= rating_end:
            last_update = req_dt.strftime("%Y-%m-%d %H:%M:%S")
        else:
            last_update = random_timestamp(rating_start, rating_end)

        rows.append({
            "volunteer_rating_id": rating_id,
            "user_id":             user["user_id"],
            "request_id":          req["req_id"],
            "rating":              rating,
            "feedback":            feedback,
            "last_update_date":    last_update,
        })
        rating_id += 1

    if len(rows) < n_rows:
        print(f"  Warning: only {len(rows)} unique pairs possible. "
              f"Increase pool size with --pool-size.")
    return rows


# ─────────────────────────────────────────────
# VALIDATION
# ─────────────────────────────────────────────

def validate(rows: list, table_name: str, pk_col: str):
    print(f"\n  Validation — {table_name}")
    print(f"     Rows generated : {len(rows):,}")
    pk_vals = [r[pk_col] for r in rows]
    dupes   = len(pk_vals) - len(set(pk_vals))
    nulls   = sum(1 for v in pk_vals if not v)
    print(f"     PK duplicates  : {dupes}  {'OK' if dupes == 0 else 'FAIL'}")
    print(f"     Null PKs       : {nulls}  {'OK' if nulls == 0 else 'FAIL'}")
    if table_name == "volunteer_rating":
        from collections import Counter
        dist  = Counter(r["rating"] for r in rows)
        pairs = [(r["user_id"], r["request_id"]) for r in rows]
        dp    = len(pairs) - len(set(pairs))
        print(f"     Rating dist    : {dict(sorted(dist.items()))}")
        print(f"     Dupe pairs     : {dp}  {'OK' if dp == 0 else 'FAIL'}")


# ─────────────────────────────────────────────
# CSV WRITER
# ─────────────────────────────────────────────

def write_csv(rows: list, filename: str):
    if not rows:
        return
    path = OUTPUT_DIR / filename
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)
    print(f"  Saved {filename}: {len(rows):,} rows → {path}")


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate synthetic CSVs for request_comments and volunteer_rating"
    )
    parser.add_argument("--rows",        type=int, default=100,
                        help="Rows per table (default: 100)")
    parser.add_argument("--pool-size",   type=int, default=None,
                        help="Internal pool size override")
    parser.add_argument("--seed",        type=int, default=42,
                        help="Random seed (default: 42)")
    parser.add_argument("--users-csv",   type=str, default=None,
                        help="Path to users.csv from another team (for real FK integrity)")
    parser.add_argument("--requests-csv", type=str, default=None,
                        help="Path to request.csv from another team (for real FK integrity)")
    args = parser.parse_args()

    random.seed(args.seed)
    n_rows = args.rows

    print(f"\nSaayam Synthetic Data Generator — Issue #119")
    print(f"Tables : request_comments, volunteer_rating")
    print(f"Rows   : {n_rows:,} per table")
    print(f"Seed   : {args.seed}\n")

    # ── Load users and requests ──────────────────
    ext_users    = args.users_csv    is not None
    ext_requests = args.requests_csv is not None

    if ext_users and ext_requests:
        print("Mode: EXTERNAL CSVs — using real user_ids and req_ids for full FK integrity")
        users    = load_external_users(args.users_csv)
        requests = load_external_requests(args.requests_csv)
    elif ext_users or ext_requests:
        print("Warning: provide BOTH --users-csv and --requests-csv for full FK integrity.")
        print("Falling back to internal pool for missing source.\n")
        pool = args.pool_size or max(200, n_rows * 3)
        u_int, r_int = build_reference_pool(pool, pool)
        users    = load_external_users(args.users_csv) if ext_users else u_int
        requests = load_external_requests(args.requests_csv) if ext_requests else r_int
    else:
        print("Mode: INTERNAL POOL — generating own user_ids and req_ids")
        pool = args.pool_size or max(200, n_rows * 3)
        print(f"Pool : {pool:,} users × {pool:,} requests\n")
        users, requests = build_reference_pool(pool, pool)

    # ── Generate tables ──────────────────────────
    print("Generating request_comments...")
    comments = generate_request_comments(users, requests, n_rows)
    validate(comments, "request_comments", "comment_id")
    write_csv(comments, "request_comments.csv")

    print("\nGenerating volunteer_rating...")
    ratings = generate_volunteer_rating(users, requests, n_rows)
    validate(ratings, "volunteer_rating", "volunteer_rating_id")
    write_csv(ratings, "volunteer_rating.csv")

    print(f"\nDone. Output: {OUTPUT_DIR}/")
    print(f"  request_comments.csv  — {len(comments):,} rows")
    print(f"  volunteer_rating.csv  — {len(ratings):,} rows")
    print(f"\nOnce users.csv and request.csv are ready from the other team, run:")
    print(f"  python generate_119.py --users-csv database/mock_db/users.csv \\")
    print(f"                         --requests-csv database/mock_db/request.csv")
    print(f"  This regenerates both files with real FK consistency.\n")


if __name__ == "__main__":
    main()
