

"""
Synthetic Data Generator — Issue #119
Tables: request_comments, volunteer_rating
Schema source: database/mock-data-generation/db_info.json
Category IDs: https://github.com/saayam-for-all/request/wiki/
              1.0-MVP-Help-Categories,-Additional-Fields-&-their-Metadata

Text Generation Pipeline (3-tier, designed for ML-training-grade diversity):
    Tier 1 — Compositional Grammar: 4-slot (greeting + action + timing + followup)
             generates ~10,000+ unique combinations per category via combinatorics.
    Tier 2 — Stochastic Perturbation: synonym replacement, typo injection,
             punctuation/casing variation, temporal detail injection.
             Combined with Tier 1, produces effectively unlimited unique strings.
    Tier 3 — Diversity Validator: unique-string ratio + 4-gram frequency analysis
             ensures the corpus is ML-training-grade (no memorizable repetition).

Usage (standalone):
    python generate_119.py --rows 40000

Usage (with external CSVs from other team — preferred for full FK integrity):
    python generate_119.py --users-csv database/mock_db/users.csv \\
                           --requests-csv database/mock_db/request.csv

    When external CSVs are provided, user_id and req_id values are read
    directly from those files — guaranteeing referential integrity across
    ALL synthetic tables generated by ALL teams.

Output:
    database/mock_db/request_comments.csv
    database/mock_db/volunteer_rating.csv
"""

import csv
import random
import uuid
import re
import argparse
from datetime import datetime, timedelta
from pathlib import Path


RANDOM_SEED = 42
random.seed(RANDOM_SEED)

OUTPUT_DIR = Path("database/mock_db")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

START_DATE = datetime(2024, 1, 1)
END_DATE   = datetime(2026, 3, 1)


# ─────────────────────────────────────────────
# OFFICIAL CATEGORY HIERARCHY — materialized path IDs
# Source: https://github.com/saayam-for-all/request/wiki/
#         1.0-MVP-Help-Categories,-Additional-Fields-&-their-Metadata
# Last synced: 2026-04-14  (wiki last updated 2025-12-04 by Pallavi Chitrada)
# ─────────────────────────────────────────────

# Full help_categories table: cat_id → cat_name
HELP_CATEGORIES = {
    "0.0.0.0.0": "GENERAL_CATEGORY",
    # ── 1  Food & Essentials ──
    "1":     "FOOD_AND_ESSENTIALS",
    "1.1":   "FOOD_ASSISTANCE",
    "1.2":   "GROCERY_SHOPPING_AND_DELIVERY",
    "1.3":   "COOKING_HELP",
    "1.3.1": "MEAL_PREP_BASIC",
    "1.3.2": "FESTIVE_OR_BULK_COOKING",
    "1.3.3": "NUTRITIONAL_MEAL_PLANNING",
    "1.3.4": "CULTURAL_CUISINE_GUIDANCE",
    "1.3.5": "OTHER_COOKING_HELP",
    # ── 2  Clothing Assistance ──
    "2":     "CLOTHING_ASSISTANCE",
    "2.1":   "DONATE_CLOTHES",
    "2.2":   "BORROW_CLOTHES",
    "2.3":   "EMERGENCY_CLOTHING_ASSISTANCE",
    "2.4":   "TAILORING",
    # ── 3  Housing Assistance ──
    "3":      "HOUSING_ASSISTANCE",
    "3.1":    "LEASE_SUPPORT",
    "3.2":    "TENANT_RENT_SUPPORT",
    "3.3":    "REPAIR_MAINTENANCE_SUPPORT",
    "3.3.1":  "PLUMBING",
    "3.3.2":  "HANDYMAN",
    "3.3.3":  "ELECTRICIAN",
    "3.3.4":  "CARPENTRY",
    "3.3.5":  "GARDEN",
    "3.3.6":  "HVAC_AIR_CONDITIONING",
    "3.3.7":  "ROOFING",
    "3.3.8":  "LOCKSMITH",
    "3.3.9":  "PAINTING",
    "3.3.10": "MASONRY_OR_CONCRETE",
    "3.3.11": "METALWORK_OR_WELDING",
    "3.3.12": "POOL_AND_SPA_MAINTENANCE",
    "3.3.13": "OTHER_REPAIR_MAINTENANCE_SUPPORT",
    "3.4":    "UTILITIES_SETUP_SUPPORT",
    "3.5":    "LOOKING_FOR_RENTAL",
    "3.6":    "FIND_ROOMATE",
    "3.7":    "MOVE_IN_HELP",
    "3.8":    "BOOKING_PACKERS_MOVERS_SUPPORT",
    "3.9":    "BUY_THINGS",
    "3.10":   "SELL_THINGS",
    # ── 4  Education & Career Support ──
    "4":     "EDUCATION_CAREER_SUPPORT",
    "4.1":   "COLLEGE_APPLICATION_HELP",
    "4.2":   "SOP_ESSAY_REVIEW",
    "4.3":   "TUTORING",
    "4.3.1": "MATH",
    "4.3.2": "ENGLISH",
    "4.3.3": "SCIENCE",
    "4.3.4": "COMPUTER_SCIENCE",
    "4.3.5": "TEST_PREP",
    "4.3.6": "OTHER_SUBJECTS",
    "4.4":   "SCHOLARSHIP_KNOWLEDGE",
    "4.5":   "STUDY_GROUP_FORMATION",
    "4.6":   "CAREER_GUIDANCE",
    "4.7":   "EDUCATION_RESOURCE_SHARING",
    # ── 5  Healthcare & Wellness ──
    "5":      "HEALTHCARE_AND_WELLNESS",
    "5.1":    "MEDICAL_CONSULTATION",
    "5.1.1":  "GENERAL_CONSULTATION",
    "5.1.2":  "ENT(EAR_NOSE_AND_THROAT)",
    "5.1.3":  "DENTAL_OR_ORAL_HEALTH",
    "5.1.4":  "EYE_OR_VISION_CARE",
    "5.1.5":  "CARDIAC_OR_BLOOD_PRESSURE",
    "5.1.6":  "ORTHOPEDIC_OR_PHYSIOTHERAPY",
    "5.1.7":  "SKIN_OR_DERMATOLOGY",
    "5.1.8":  "WOMENS_OR_REPRODUCTIVE_HEALTH",
    "5.1.9":  "VACCINATIONS_AND_PREVENTIVE_SCREENINGS",
    "5.1.10": "PEDIATRICS_OR_CHILD_HEALTH",
    "5.1.11": "OTHER_MEDICAL_CONCERN",
    "5.2":    "MEDICINE_DELIVERY",
    "5.3":    "MENTAL_WELLBEING_SUPPORT",
    "5.4":    "MEDICATION_REMINDERS",
    "5.5":    "HEALTH_EDUCATION_GUIDANCE",
    # ── 6  Elderly Community Assistance ──
    "6":   "ELDERLY_COMMUNITY_ASSISTANCE",
    "6.1": "SENIOR_RELOCATION_SUPPORT",
    "6.2": "DIGITAL_SUPPORT_FOR_SENIORS",
    "6.3": "MEDICATION_MANAGEMENT",
    "6.4": "MEDICAL_DEVICES_SETUP",
    "6.5": "ERRANDS_EVENTS_TRANSPORTATION",
    "6.6": "TRANSPORTATION_APPOINTMENTS_EVENTS",
    "6.7": "SCHEDULING_APPOINTMENTS_OR_TASKS",
    "6.8": "SOCIAL_CONNECTION",
    "6.9": "MEAL_SUPPORT",
}

# Parent-to-children map (from help_categories_map table on wiki)
# Only LEAF nodes are valid for req_cat_id — requests are filed
# under the most specific subcategory, not intermediate parents.
CATEGORY_TREE = {
    "1":   ["1.1", "1.2", "1.3.1", "1.3.2", "1.3.3", "1.3.4", "1.3.5"],
    "2":   ["2.1", "2.2", "2.3", "2.4"],
    "3":   ["3.1", "3.2",
            "3.3.1", "3.3.2", "3.3.3", "3.3.4", "3.3.5", "3.3.6",
            "3.3.7", "3.3.8", "3.3.9", "3.3.10", "3.3.11", "3.3.12", "3.3.13",
            "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10"],
    "4":   ["4.1", "4.2",
            "4.3.1", "4.3.2", "4.3.3", "4.3.4", "4.3.5", "4.3.6",
            "4.4", "4.5", "4.6", "4.7"],
    "5":   ["5.1.1", "5.1.2", "5.1.3", "5.1.4", "5.1.5", "5.1.6",
            "5.1.7", "5.1.8", "5.1.9", "5.1.10", "5.1.11",
            "5.2", "5.3", "5.4", "5.5"],
    "6":   ["6.1", "6.2", "6.3", "6.4", "6.5", "6.6", "6.7", "6.8", "6.9"],
    "0.0.0.0.0": ["0.0.0.0.0"],  # General fallback
}

# Weighted to reflect real usage — Food/Healthcare/Education most common
PARENT_CATEGORIES = ["1", "2", "3", "4", "5", "6", "0.0.0.0.0"]
PARENT_WEIGHTS    = [0.22, 0.08, 0.17, 0.18, 0.20, 0.10, 0.05]


def get_parent_cat_id(cat_id: str) -> str:
    """Derive parent cat_id from a materialized path.
    '3.3.7' → '3', '5.1.3' → '5', '2.1' → '2', '1' → '1'
    """
    parts = cat_id.split(".")
    if len(parts) <= 1:
        return cat_id
    return parts[0]


def random_category() -> tuple:
    """Pick a realistic (parent_cat_id, leaf_cat_id) pair.
    Returns official materialized path IDs — ready for req_cat_id.
    """
    parent = random.choices(PARENT_CATEGORIES, weights=PARENT_WEIGHTS, k=1)[0]
    leaf   = random.choice(CATEGORY_TREE[parent])
    return parent, leaf


# ═══════════════════════════════════════════════════════════════
# TIER 1 — COMPOSITIONAL GRAMMAR ENGINE
# Instead of N fixed templates, we have 4 slots × M variants each
# → M^4 combinatorial unique strings per category.
# ═══════════════════════════════════════════════════════════════

# Structure per category: greeting + action + timing + followup
# Empty strings ("") are valid — they produce natural variation
# (some real comments have no greeting, some skip timing, etc.)

COMMENT_GRAMMAR = {
    "1": {  # FOOD_AND_ESSENTIALS
        "greeting": [
            "Hi there,", "Hello,", "Good news on the food request —",
            "Quick note:", "Just following up.", "Checking in —",
            "Hey,", "Hi,", "Good morning,", "Good afternoon,",
            "Food coordination update:", "Pantry note —",
            "Meal update:", "Delivery status —", "",
        ],
        "action": [
            "grocery delivery has been arranged",
            "we connected you with the local food bank",
            "meal prep was completed and dropped off",
            "a volunteer picked up the items you needed",
            "food assistance has been processed",
            "we found a pantry near your area",
            "your meal planning request is being handled",
            "a volunteer is coordinating your delivery",
            "the food package is ready to go",
            "your grocery list is fully covered",
            "a local restaurant donated meals for you",
            "we reviewed and shared the nutritional plan",
        ],
        "timing": [
            "for tomorrow morning.",
            "— pickup is available Tuesday.",
            "and containers are at your door.",
            "with an ETA of about 2 hours.",
            "for this weekend.",
            "and should arrive by end of day.",
            "— confirmation sent to your email.",
            "for the upcoming week.",
            "and is ready for collection.",
            "— details in the notification you received.",
            "within the next couple of hours.",
            "and the pantry confirmed availability.",
            "— your name is on the list for Wednesday.",
            "once the driver finishes the current route.",
            "and everything matched your dietary notes.",
            "— a text was sent with the address.",
            "by early afternoon at the latest.",
            "and labeled with your request number.",
            "",
        ],
        "followup": [
            "", "", "", "",  # ~50% no followup (weighted by repetition)
            "Drop us a message once you've received everything.",
            "Any issues with the delivery, just reply here.",
            "We can arrange another round next week if helpful.",
            "Ping the thread when the groceries arrive.",
            "Tag us if the portions weren't sufficient.",
            "Marking this as in-progress — update us after pickup.",
            "All set from our side — circle back if anything's off.",
            "Hoping the meal plan works well for your household.",
            "Would love to hear how the food bank experience went.",
        ],
    },
    "2": {  # CLOTHING_ASSISTANCE
        "greeting": [
            "Hi,", "Hello,", "Good news —", "Quick update:",
            "Following up.", "Hey,", "Just a note —", "",
        ],
        "action": [
            "I have some clothing items to donate",
            "happy to help with the tailoring request",
            "we noted the emergency clothing need",
            "we located donated items that match your size",
            "a volunteer has gently used clothes in your size range",
            "the clothing drop-off is all coordinated",
            "tailoring service is available through a local volunteer",
            "we matched your borrow request with a donor",
            "we found suitable items from the donation pool",
            "a shelter nearby has clothing available for pickup",
        ],
        "timing": [
            "— can connect offline to arrange.",
            "and pickup is available this week.",
            "— items will be delivered by Thursday.",
            "— please share your preferred pickup time.",
            "for this weekend at the community center.",
            "— details sent via message.",
            "and everything is packed and ready.",
            "",
        ],
        "followup": [
            "", "", "",
            "Hoping the sizes are a good match.",
            "Confirm pickup whenever convenient for you.",
            "Reply with your thoughts once you try them on.",
            "Swing by the center anytime this week to collect.",
            "If anything doesn't fit, we'll swap it out.",
            "We still have more in the donation pool — say the word.",
            "Tag us once the drop-off is completed.",
            "Glad we could connect you — stay in touch.",
        ],
    },
    "3": {  # HOUSING_ASSISTANCE
        "greeting": [
            "Hi,", "Hello,", "Housing update:", "Good news —",
            "Progress on your repair:", "Just following up —",
            "Hey,", "Checking in on the request:", "", "",
        ],
        "action": [
            "we contacted a plumber for you",
            "lease support is done — we reviewed the contract",
            "move-in help is coordinated with volunteers",
            "the electrician visited and resolved the issue",
            "rental listings are ready for your area",
            "we made a roommate connection for you",
            "HVAC technician availability is confirmed",
            "the handyman completed the repair",
            "locksmith service is all lined up",
            "we got the painting job estimate back",
            "a contractor reviewed the roofing issue",
            "we shared utilities setup guidance",
            "packers and movers quotes are gathered",
        ],
        "timing": [
            "— appointment is scheduled for Saturday.",
            "and flagged a few key clauses to review.",
            "— 3 volunteers are available next weekend.",
            "— marking this request as resolved.",
            "based on your budget and location preferences.",
            "— please follow up with them directly.",
            "for Friday afternoon.",
            "— the visit is set for Monday morning.",
            "and a quote was sent to your email.",
            "within the timeframe you specified.",
            "once the permit gets approved.",
            "and photos of the work are attached.",
            "ahead of your lease renewal deadline.",
            "with a backup contractor on standby.",
            "at a rate that fits your budget.",
            "and the landlord has been notified.",
            "by the crew we partnered with locally.",
            "",
        ],
        "followup": [
            "", "", "", "",
            "Confirm whether the appointment time works.",
            "Reply here once the repair is finished.",
            "We can send a second technician if the fix didn't hold.",
            "Still looking at backup options in case this falls through.",
            "Drop a note here once the contractor wraps up.",
            "Ping me if you want additional rental listings.",
            "Standing by for your go-ahead to book the movers.",
            "Will circle back mid-week to see how things went.",
        ],
    },
    "4": {  # EDUCATION_CAREER_SUPPORT
        "greeting": [
            "Hi,", "Hello,", "Great news —", "Study update:",
            "Hey there,", "Quick academic note:", "Tutoring note:", "",
        ],
        "action": [
            "I can help with tutoring on weekends",
            "we reviewed the SOP draft — feedback sent",
            "college application guidance is ready",
            "connecting you with a scholarship database",
            "a career guidance session is on the calendar",
            "the study group is formed and ready to go",
            "we reviewed your resume with detailed notes",
            "mock interview practice is available",
            "a tutor matched your subject and schedule",
            "we compiled education resource links for you",
            "your essay draft feedback is ready",
            "we identified a mentor in your field",
        ],
        "timing": [
            "— available via Zoom.",
            "via email earlier today.",
            "for next Tuesday at 4 PM.",
            "for your field of study.",
            "— 4 members so far, meeting every Sunday.",
            "— take a look at your inbox when you can.",
            "and can start this week.",
            "— details in the shared document.",
            "through the platform's tutoring scheduler.",
            "with materials attached as a PDF.",
            "during your preferred evening window.",
            "aligned with the upcoming application deadline.",
            "and a second session is tentatively booked.",
            "at the campus library meeting room.",
            "using the video link we set up.",
            "and notes were saved to the shared drive.",
            "ready for your review before the weekend.",
            "",
        ],
        "followup": [
            "", "", "", "",
            "Send over your availability for the next session.",
            "Another draft revision is totally fine — just upload it.",
            "We can match you with a different tutor if the fit isn't right.",
            "Reply with any questions after reviewing the feedback.",
            "The mentor is excited to connect — confirm the slot.",
            "Tag us if you want to expand the study group.",
            "Wishing you the best on the application deadline.",
            "Share how the mock interview went when you get a chance.",
        ],
    },
    "5": {  # HEALTHCARE_AND_WELLNESS
        "greeting": [
            "Hi,", "Hello,", "Health update for you:",
            "Good news —", "Medical note:", "Checking in —",
            "Just following up.", "Hi there,",
            "Wellness update:", "Quick medical note —",
            "Care team update:", "Following up on your health request:",
            "Some news on your care:", "Health coordination update:",
            "On the medical front —", "",
        ],
        "action": [
            "a general consultation is arranged via telemedicine",
            "medication delivery is confirmed",
            "the mental wellbeing session went well",
            "we shared a dental referral for you",
            "we got the medication reminder schedule working",
            "a physiotherapy volunteer was found in your area",
            "an eye care specialist referral is ready",
            "a vaccination appointment is booked",
            "a volunteer doctor will follow up with you",
            "the health education session materials are ready",
            "we coordinated a dermatology consult",
            "the prescription was verified and is being processed",
        ],
        "timing": [
            "with a volunteer doctor.",
            "for tomorrow.",
            "— person is doing noticeably better.",
            "— contact details shared via message.",
            "on their phone — all set.",
            "and they can see you this week.",
            "— appointment is confirmed for Thursday.",
            "and results should be available soon.",
            "through a telehealth link we sent over.",
            "once the pharmacy confirms stock.",
            "and the specialist will call you directly.",
            "by the end of business today.",
            "— the nurse practitioner is on standby.",
            "ahead of your scheduled checkup.",
            "and insurance pre-auth has been handled.",
            "at the community health center downtown.",
            "with a two-week follow-up reminder built in.",
            "",
        ],
        "followup": [
            "", "", "", "",
            "Update the thread once you've spoken with the doctor.",
            "Reply if a follow-up appointment would be useful.",
            "We can refer you to a different specialist anytime.",
            "Wishing you a speedy recovery — post an update soon.",
            "Confirm that the prescription details are correct.",
            "The care team is on standby if symptoms return.",
            "Tag us after the telemedicine call wraps up.",
            "We'll look into additional wellness resources for you.",
        ],
    },
    "6": {  # ELDERLY_COMMUNITY_ASSISTANCE
        "greeting": [
            "Hi,", "Hello,", "Good news —", "Senior care note:",
            "Just checking in.", "Hey there,", "Care update:", "",
        ],
        "action": [
            "transportation to the appointment is all arranged",
            "helped set up video calling on the tablet",
            "we organized the medication schedule",
            "a grocery run was completed — items dropped off",
            "a social visit was done — had a great conversation",
            "digital support session is complete",
            "medical device setup is finished",
            "errand support is coordinated for the week",
            "we took care of the appointment scheduling",
            "a meal delivery plan is now active",
            "we matched a companion volunteer for regular visits",
        ],
        "timing": [
            "for Thursday.",
            "— all good now, everything is working.",
            "into a weekly pill box.",
            "at the door earlier today.",
            "and will follow up again next week.",
            "— they were really happy with the help.",
            "for the coming month.",
            "— confirmed with the care team.",
            "",
        ],
        "followup": [
            "", "", "",
            "We'll pencil in another visit for next week.",
            "Ring us if the device gives any trouble.",
            "The companion volunteer will be in touch directly.",
            "Share how the appointment goes when you can.",
            "Glad the setup went smoothly — call if anything changes.",
            "We have more meal options if the current plan doesn't suit.",
            "Caregiver notes have been shared with the family.",
            "Standing by for the next errand request.",
        ],
    },
    "0.0.0.0.0": {  # GENERAL_CATEGORY
        "greeting": [
            "Hi,", "Hello,", "Status change:", "Quick note:",
            "Hey,", "Heads up:", "FYI:", "",
        ],
        "action": [
            "your request is received and under review",
            "we need a few more details to find the right volunteer",
            "this is now resolved",
            "escalating to the team for faster resolution",
            "a volunteer is assigned to your request",
            "we're actively looking for the right match",
            "the request was forwarded to the relevant team",
            "your request is in the queue and will be picked up soon",
        ],
        "timing": [
            "— will follow up shortly.",
            "— please update the request with more info.",
            "— closing the request now.",
            "— expect a response within 24 hours.",
            "— check your messages for next steps.",
            "",
        ],
        "followup": [
            "", "", "",
            "Is anything else outstanding on this request?",
            "Appreciate your patience while we get this sorted.",
            "Drop a reply if the situation has changed.",
            "We'll bump this in the queue if no response by Friday.",
            "The team is on it — expect movement shortly.",
            "Close this ticket yourself once everything is resolved.",
            "Post an update so we can track progress.",
        ],
    },
}


# ── FEEDBACK GRAMMAR — same compositional approach for ratings ──

FEEDBACK_GRAMMAR = {
    5: {
        "opener": [
            "The volunteer was incredibly helpful",
            "Outstanding support",
            "Absolutely wonderful experience",
            "Truly above and beyond",
            "Could not have asked for better help",
            "The help I received was life-changing",
            "Phenomenal support from start to finish",
            "Exceptional in every way",
            "Best experience I've ever had with volunteer help",
            "Genuinely grateful for the help",
            "What an amazing person",
            "Exceeded all my expectations",
            "This restored my faith in community",
            "I was blown away by the support",
            "Incredibly kind and thoughtful",
            "Everything was handled perfectly",
            "A truly remarkable volunteer",
            "I felt heard and supported the entire time",
            "Went far beyond what was expected",
            "Nothing short of excellence",
            "World-class kindness on display",
            "The level of care was unmatched",
            "Exactly the help I desperately needed",
            "A shining example of what volunteers should be",
        ],
        "detail": [
            "and kind — made a real difference.",
            "— very professional and understanding throughout.",
            "— showed up on time and went above and beyond.",
            "— fast response and genuine care.",
            "— knowledgeable, compassionate, and efficient.",
            "— the volunteer truly understood my situation.",
            "— they took the time to explain everything clearly.",
            "— so patient and thorough.",
            "— felt like they really cared about helping.",
            "— everything was handled smoothly.",
            "— the communication was top-notch from day one.",
            "— they followed up without me even asking.",
            "— went out of their way to make things easier.",
            "— resolved things much faster than I expected.",
            "— kept me informed at every single step.",
            "— treated me with dignity and respect.",
            "— the whole process felt effortless on my end.",
            "— I never once had to chase for updates.",
            "— went beyond what I asked for and covered extra ground.",
            "— the attention to detail was incredible.",
            "— made a stressful situation feel manageable.",
            "— their expertise was immediately obvious.",
            "— warm, professional, and extremely reliable.",
            "— genuinely one of the best helpers I've encountered.",
            "— their compassion made all the difference here.",
            "— a model of what community support should look like.",
            "— efficient without ever feeling transactional.",
            "— struck the perfect balance of warmth and competence.",
            "— left me feeling supported instead of a burden.",
            "— brought real expertise and a personal touch.",
            "— followed through on every single commitment they made.",
            "",
        ],
        "recommend": [
            "", "", "", "", "",  # ~40% no recommend tag
            "Highly recommend.",
            "Would absolutely reach out again.",
            "Thank you so much.",
            "Five stars without question.",
            "Grateful beyond words.",
            "This is exactly what Saayam is about.",
            "Will definitely request help here again.",
            "Can't thank them enough.",
            "A+ from start to finish.",
            "An inspiration to the community.",
            "Please assign them to others — they deserve recognition.",
            "Bookmarking this volunteer for next time.",
            "Proof that strangers can make a real impact.",
            "The gold standard for volunteer support.",
            "If every interaction was like this, the world would be better.",
            "Telling everyone I know about Saayam.",
            "My family is so grateful.",
            "Sending good vibes their way — truly earned.",
            "Top-notch human being.",
            "Made my whole week better.",
        ],
    },
    4: {
        "opener": [
            "Very helpful overall",
            "Good experience",
            "Appreciated the support",
            "Solid help from the volunteer",
            "Great follow-through",
            "Quite pleased with the outcome",
            "The volunteer was thorough",
            "Overall a positive experience",
            "Happy with the assistance provided",
            "The support was reliable",
            "Things went well for the most part",
            "The volunteer clearly tried their best",
            "Pleasantly surprised by the quality",
            "Really solid effort all around",
            "The help was dependable and thoughtful",
            "Came away feeling well taken care of",
            "A genuinely good interaction",
            "Better than my previous experiences",
            "The volunteer knew exactly what to do",
            "Smooth process with only small hiccups",
        ],
        "detail": [
            "— minor delay but quality of support was great.",
            "— the volunteer was communicative and reliable.",
            "— would have liked slightly faster response.",
            "— went the extra mile in most areas.",
            "— a small miscommunication early on but resolved well.",
            "— just a few small things could be improved.",
            "— the effort was clear and appreciated.",
            "— almost perfect, just minor timing issues.",
            "— really solid work on the main request.",
            "— a couple of hiccups but nothing major.",
            "— they kept me informed throughout.",
            "— slightly delayed start but finished strong.",
            "— one or two details got missed but overall great.",
            "— the core task was done well, edges need polish.",
            "— I could tell they were juggling multiple requests.",
            "— the final result was better than the process suggested.",
            "— a tiny miscommunication about the timeline, nothing big.",
            "— initial response was slow but once started, very efficient.",
            "— impressed by the depth of knowledge, just wish it was quicker.",
            "— reliable execution, with just a hint of polish missing.",
            "— got the job done well despite a rocky start.",
            "— good outcome even if the journey had some bumps.",
            "— professional throughout, though the pace could pick up.",
            "",
        ],
        "recommend": [
            "", "", "", "", "",  # ~40% no recommend tag
            "Would recommend to others.",
            "Would request assistance here again.",
            "Thank you for the effort.",
            "Mostly great — a few things to polish.",
            "Good work overall.",
            "Glad I reached out.",
            "Solid experience — close to perfect.",
            "Appreciate the quick turnaround.",
            "Would pair with this volunteer again.",
            "A strong four out of five.",
            "Just a notch below perfect — still impressed.",
            "Definitely a net positive experience.",
            "Minor tweaks and this would be flawless.",
            "Reliable help when I needed it most.",
            "Happy with the outcome despite the small bumps.",
            "Would give five stars if timing was tighter.",
            "Very much worth the wait.",
            "Better than I expected going in.",
        ],
    },
    3: {
        "opener": [
            "Decent help",
            "The volunteer was helpful",
            "Got the help I needed eventually",
            "Good intentions",
            "Satisfactory overall",
            "Average experience",
            "It was okay",
            "Mixed feelings about this one",
            "Not bad but not great either",
            "The outcome was acceptable",
            "Partially met my expectations",
            "Could have gone better",
        ],
        "detail": [
            "but took longer than expected to get started.",
            "but communication could be improved.",
            "— average experience overall.",
            "but the coordination could use improvement.",
            "— did their best with limited resources.",
            "but I expected a bit more follow-through.",
            "— some gaps in communication along the way.",
            "but the end result was fine.",
            "— needed more clarity on next steps.",
            "— the process felt a bit disorganized.",
            "— had to reach out multiple times for updates.",
            "",
        ],
        "recommend": [
            "", "", "", "",
            "Room for improvement.",
            "Hope it goes smoother next time.",
            "Might try again in the future.",
            "Okay for now but I expected more.",
            "Not bad, not amazing — right in the middle.",
            "The potential is there but execution needs work.",
            "A passable experience — nothing more.",
            "Would consider trying once more.",
            "Could be great with better follow-through.",
            "Three stars feels accurate.",
            "Serviceable but forgettable.",
        ],
    },
    2: {
        "opener": [
            "Poor communication",
            "The help provided did not fully match",
            "Felt rushed",
            "Volunteer was late",
            "Disappointing experience",
            "Below expectations",
            "Not what I was hoping for",
            "Struggled to get proper help",
            "The coordination fell apart",
            "Hard to get a response",
            "Left me waiting for too long",
        ],
        "detail": [
            "— had to follow up multiple times.",
            "what was actually needed.",
            "— did not take enough time to understand the situation.",
            "and did not complete the task as agreed.",
            "— it felt like the volunteer was distracted.",
            "— important details were overlooked.",
            "— the coordination was poor from the start.",
            "— things went downhill after the initial contact.",
            "— promised a timeline that was not met.",
            "— felt like my request was low priority.",
            "",
        ],
        "recommend": [
            "", "", "",
            "Hope the process improves.",
            "Would appreciate better matching next time.",
            "Frustrating but I understand volunteers are busy.",
            "Need more accountability in the process.",
            "Hesitant to try again after this.",
            "Expected much more from the platform.",
            "Not the experience I was promised.",
            "Will give it one more shot before giving up.",
            "Please look into what went wrong here.",
        ],
    },
    1: {
        "opener": [
            "The volunteer did not show up",
            "No follow-up after initial contact",
            "The help provided was inadequate",
            "Volunteer was unresponsive",
            "Extremely disappointing",
            "Nothing was done despite the assignment",
            "Complete no-show",
            "Very frustrating experience",
            "Absolutely zero help received",
            "The worst volunteer interaction I've encountered",
            "Total lack of communication",
        ],
        "detail": [
            "as scheduled — very disappointing.",
            "— left me in a difficult spot.",
            "for my situation.",
            "after being assigned — frustrating experience.",
            "— I had to find help elsewhere.",
            "— no communication at all.",
            "— I waited days with no update.",
            "— completely wasted my time.",
            "— had to escalate just to get a response.",
            "— still unresolved after weeks.",
            "",
        ],
        "recommend": [
            "", "", "",
            "I hope this gets addressed.",
            "Very let down by the experience.",
            "Would not recommend based on this interaction.",
            "Something needs to change.",
            "Please fix the matching process.",
            "Lost trust in the platform after this.",
            "Considering other options at this point.",
            "This should not happen to anyone else.",
            "Zero confidence in the process now.",
            "Worst case scenario came true.",
        ],
    },
}

# Category-specific context fragments for feedback — adds a 4th diversity axis
# These get injected ~40% of the time to make feedback reference the actual help type
FEEDBACK_CATEGORY_CONTEXT = {
    "1": [
        "The food delivery", "The grocery assistance", "The meal prep help",
        "The nutritional guidance", "The food bank connection", "The cooking help",
        "Getting the groceries", "The food support",
    ],
    "2": [
        "The clothing donation", "The tailoring help", "The emergency clothing",
        "The clothing assistance", "Finding the right clothes",
    ],
    "3": [
        "The plumbing repair", "The lease review", "The move-in help",
        "The housing assistance", "The repair work", "The rental search",
        "Getting the electrician", "The maintenance support", "The roommate search",
    ],
    "4": [
        "The tutoring session", "The career guidance", "The SOP review",
        "The college application help", "The study group setup", "The essay feedback",
        "The scholarship search", "The mentoring session",
    ],
    "5": [
        "The medical consultation", "The medication delivery", "The mental health support",
        "The health guidance", "The dental referral", "The telemedicine session",
        "Getting the prescription", "The wellness check",
    ],
    "6": [
        "The transportation help", "The digital support session", "The medication management",
        "The senior assistance", "The companion visit", "The errand help",
        "The device setup", "The appointment scheduling",
    ],
    "0.0.0.0.0": [
        "The general assistance", "The support provided", "The help received",
    ],
}


# ═══════════════════════════════════════════════════════════════
# TIER 2 — STOCHASTIC PERTURBATION LAYER
# Applies controlled noise on top of composed text:
#   - Synonym replacement (30% per matchable word)
#   - Typo injection (2% — real users make typos)
#   - Punctuation variation (15%)
#   - Casing variation (8% — some users type all lowercase)
# ═══════════════════════════════════════════════════════════════

SYNONYM_MAP = {
    "arranged":      ["set up", "coordinated", "scheduled", "organized", "lined up"],
    "dropped off":   ["delivered", "left at your door", "handed over", "brought over"],
    "helpful":       ["supportive", "great", "wonderful", "fantastic", "terrific"],
    "volunteer":     ["helper", "team member", "person assigned", "supporter"],
    "follow up":     ["check back", "circle back", "reach out again", "get back to you"],
    "resolved":      ["fixed", "taken care of", "handled", "sorted out", "cleared up"],
    "scheduled":     ["booked", "arranged", "set up", "confirmed", "penciled in"],
    "professional":  ["thorough", "skilled", "capable", "dedicated", "competent"],
    "coordinated":   ["organized", "arranged", "set up", "put together", "handled"],
    "confirmed":     ["verified", "locked in", "finalized", "double-checked"],
    "available":     ["free", "open", "ready", "on hand", "accessible"],
    "completed":     ["finished", "done", "wrapped up", "taken care of"],
    "provided":      ["shared", "given", "offered", "supplied", "passed along"],
    "contacted":     ["reached out to", "got in touch with", "called", "messaged"],
    "reviewed":      ["looked over", "checked", "gone through", "examined"],
    "sent":          ["forwarded", "shared", "emailed", "passed along"],
    "matched":       ["paired", "connected", "linked up", "found a fit for"],
    "grateful":      ["thankful", "appreciative", "so glad", "really happy"],
    "disappointing": ["frustrating", "let down", "unfortunate", "disheartening"],
    "inadequate":    ["insufficient", "not enough", "lacking", "subpar"],
    "recommend":     ["suggest others try", "endorse", "vouch for", "advocate for"],
    "experience":    ["interaction", "encounter", "process", "journey"],
    "amazing":       ["incredible", "outstanding", "remarkable", "extraordinary"],
    "impressed":     ["blown away", "pleasantly surprised", "struck by", "delighted"],
    "improvement":   ["polish", "refinement", "growth", "development"],
    "communication": ["responsiveness", "updates", "messaging", "coordination"],
    "quick":         ["fast", "prompt", "speedy", "rapid", "swift"],
    "situation":     ["circumstances", "case", "matter", "issue"],
    "support":       ["help", "assistance", "aid", "backing"],
    "wonderful":     ["fantastic", "terrific", "lovely", "superb", "stellar"],
    "outstanding":   ["exceptional", "remarkable", "first-rate", "brilliant"],
    "blown away":    ["deeply moved", "truly stunned", "completely wowed", "thoroughly impressed"],
    "above and beyond": ["more than expected", "beyond the call", "extra effort", "way past the ask"],
    "from start to finish": ["throughout the process", "the whole way through", "from beginning to end"],
    "pleased":       ["satisfied", "content", "happy", "glad"],
    "has been":      ["is now", "was", "got", "is"],
}

# Day/time fragments injected for temporal realism
_DAYS  = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
_TIMES = ["morning", "afternoon", "evening", "around noon", "at 3 PM", "at 10 AM",
          "after lunch", "first thing in the morning", "by end of day"]


def _synonym_replace(text: str) -> str:
    """Replace 0-2 words/phrases with synonyms (30% chance each)."""
    result = text
    for word, synonyms in SYNONYM_MAP.items():
        if word in result.lower() and random.random() < 0.30:
            replacement = random.choice(synonyms)
            result = re.sub(
                re.escape(word), replacement, result,
                count=1, flags=re.IGNORECASE
            )
    return result


def _inject_typo(text: str) -> str:
    """Swap two adjacent characters (2% chance). Real users make typos."""
    if random.random() < 0.02 and len(text) > 4:
        idx = random.randint(1, len(text) - 3)
        text = text[:idx] + text[idx + 1] + text[idx] + text[idx + 2:]
    return text


def _vary_punctuation(text: str) -> str:
    """Alter ending punctuation (15% chance)."""
    if random.random() < 0.15 and text:
        text = text.rstrip('.!,')
        text += random.choice(['.', '!', '!!', ' :)', '.', '...'])
    return text


def _vary_casing(text: str) -> str:
    """Some users type all lowercase (8% chance)."""
    if random.random() < 0.08:
        text = text.lower()
    return text


def _inject_temporal_detail(text: str) -> str:
    """10% chance to swap generic timing with a specific day/time."""
    if random.random() < 0.10:
        day  = random.choice(_DAYS)
        time = random.choice(_TIMES)
        # Try to replace vague timing markers
        for vague in ["this week", "soon", "shortly", "for the upcoming week"]:
            if vague in text.lower():
                text = re.sub(re.escape(vague), f"on {day} {time}",
                              text, count=1, flags=re.IGNORECASE)
                break
    return text


def perturb(text: str) -> str:
    """Full Tier 2 perturbation pipeline."""
    text = _synonym_replace(text)
    text = _inject_temporal_detail(text)
    text = _inject_typo(text)
    text = _vary_punctuation(text)
    text = _vary_casing(text)
    return text


# ═══════════════════════════════════════════════════════════════
# TIER 1 + TIER 2 COMBINED — TEXT GENERATORS
# ═══════════════════════════════════════════════════════════════

def compose_comment(parent_cat_id: str) -> str:
    """Tier 1: Assemble a comment from grammar slots."""
    grammar = COMMENT_GRAMMAR.get(parent_cat_id, COMMENT_GRAMMAR["0.0.0.0.0"])
    parts = [
        random.choice(grammar["greeting"]),
        random.choice(grammar["action"]),
        random.choice(grammar["timing"]),
        random.choice(grammar["followup"]),
    ]
    return " ".join(p for p in parts if p).strip()


def compose_feedback(rating: int, parent_cat_id: str = "0.0.0.0.0") -> str:
    """Tier 1: Assemble feedback text from grammar slots + category context."""
    grammar = FEEDBACK_GRAMMAR.get(rating, FEEDBACK_GRAMMAR[3])
    parts = [
        random.choice(grammar["opener"]),
        random.choice(grammar["detail"]),
        random.choice(grammar["recommend"]),
    ]
    base = " ".join(p for p in parts if p).strip()
    # 40% chance: prepend category-specific context
    if random.random() < 0.40:
        ctx_pool = FEEDBACK_CATEGORY_CONTEXT.get(
            parent_cat_id, FEEDBACK_CATEGORY_CONTEXT["0.0.0.0.0"]
        )
        ctx = random.choice(ctx_pool)
        base = f"{ctx} was great. {base}" if rating >= 4 else f"{ctx} fell short. {base}"
    return base


def pick_comment(parent_cat_id: str, leaf_cat_id: str) -> str:
    """Generate a comment using Tier 1 (composition) + Tier 2 (perturbation)."""
    base = compose_comment(parent_cat_id)
    # 30% chance: append subcategory context
    if random.random() < 0.3 and leaf_cat_id != "0.0.0.0.0":
        cat_name = HELP_CATEGORIES.get(leaf_cat_id, leaf_cat_id)
        readable = cat_name.replace("_", " ").title()
        base += f" (Re: {readable})"
    return perturb(base)


def pick_feedback(rating: int, parent_cat_id: str = "0.0.0.0.0") -> str:
    """Generate feedback using Tier 1 (composition) + Tier 2 (perturbation)."""
    return perturb(compose_feedback(rating, parent_cat_id))


# ═══════════════════════════════════════════════════════════════
# TIER 3 — DIVERSITY VALIDATOR
# Ensures generated corpus is ML-training-grade:
#   - Unique string ratio (target ≥ 85%)
#   - No single 4-gram dominates (target: max 1% frequency)
#   - Reports stats so we know exactly where we stand
# ═══════════════════════════════════════════════════════════════

def validate_text_diversity(texts: list, label: str,
                            min_unique_ratio: float = 0.80,
                            max_ngram_freq: float = 0.02) -> None:
    """Print diversity diagnostics for a generated text corpus."""
    from collections import Counter

    n = len(texts)
    unique = len(set(texts))
    ratio  = unique / n if n > 0 else 0

    # 4-gram frequency analysis
    ngram_counts = Counter()
    for t in texts:
        words = t.lower().split()
        for i in range(len(words) - 3):
            ngram_counts[tuple(words[i:i + 4])] += 1

    max_freq      = max(ngram_counts.values()) / n if ngram_counts else 0
    top_ngram     = ngram_counts.most_common(1)[0] if ngram_counts else (("—",), 0)
    total_unique  = len(ngram_counts)

    print(f"\n  Diversity — {label}")
    print(f"     Total texts        : {n:,}")
    print(f"     Unique texts       : {unique:,}  ({100 * ratio:.1f}%)"
          f"  {'OK' if ratio >= min_unique_ratio else 'LOW — consider more grammar slots'}")
    print(f"     Unique 4-grams     : {total_unique:,}")
    print(f"     Max 4-gram freq    : {100 * max_freq:.2f}%"
          f"  {'OK' if max_freq <= max_ngram_freq else 'HIGH — most repeated:'}")
    if max_freq > max_ngram_freq:
        print(f"       Most common      : {' '.join(top_ngram[0])} ({top_ngram[1]:,}×)")

RATING_WEIGHTS = [0.04, 0.06, 0.12, 0.33, 0.45]


# LOCATION POOL — US cities realistic for as per saayam app

LOCATIONS = [
    "Tampa, FL", "Chicago, IL", "New York, NY", "Houston, TX",
    "Phoenix, AZ", "Philadelphia, PA", "San Antonio, TX",
    "San Diego, CA", "Dallas, TX", "San Jose, CA",
    "Austin, TX", "Jacksonville, FL", "Detroit, MI",
    "Columbus, OH", "Memphis, TN", "Atlanta, GA",
    "Seattle, WA", "Denver, CO", "Boston, MA", "Miami, FL",
    "Portland, OR", "Las Vegas, NV", "Minneapolis, MN", "Charlotte, NC",
]


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def random_timestamp(start: datetime, end: datetime) -> str:
    if start >= end:
        return start.strftime("%Y-%m-%d %H:%M:%S")
    delta = end - start
    random_seconds = random.randint(0, int(delta.total_seconds()))
    return (start + timedelta(seconds=random_seconds)).strftime("%Y-%m-%d %H:%M:%S")


def make_user_id() -> str:
    return f"cognito_{uuid.UUID(int=random.getrandbits(128), version=4)}"


def make_request_id() -> str:
    return f"REQ-{str(uuid.UUID(int=random.getrandbits(128), version=4))[:8].upper()}"


# ─────────────────────────────────────────────
# LOAD EXTERNAL CSVs (when provided by other team)
# ─────────────────────────────────────────────

def load_external_users(filepath: str) -> list:
    """
    Load user_ids from the users.csv generated by another team.
    Expects a CSV with at minimum a 'user_id' column.
    """
    users = []
    with open(filepath, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            users.append({"user_id": row["user_id"]})
    print(f"  Loaded {len(users):,} users from {filepath}")
    return users


def load_external_requests(filepath: str) -> list:
    """
    Load request data from request.csv generated by another team.
    Expects columns: req_id, req_cat_id (or req_cat), req_loc, created_at (or req_created_at)
    Column names are flexible — we try common variants.
    """
    requests = []
    with open(filepath, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        cols = reader.fieldnames or []

        # Detect column name variants
        id_col  = next((c for c in cols if 'req_id' in c.lower()), None)
        cat_col = next((c for c in cols if 'cat' in c.lower()), None)
        loc_col = next((c for c in cols if 'loc' in c.lower()), None)
        dt_col  = next((c for c in cols if 'creat' in c.lower() or 'date' in c.lower()), None)

        for row in reader:
            # Parse created_at — fall back to a random date if missing/malformed
            raw_dt = row.get(dt_col, "") if dt_col else ""
            try:
                created_at = datetime.strptime(raw_dt[:19], "%Y-%m-%d %H:%M:%S")
            except Exception:
                created_at = START_DATE + timedelta(
                    days=random.randint(0, (END_DATE - START_DATE).days)
                )

            # Map category to official parent cat_id
            raw_cat = row.get(cat_col, "0.0.0.0.0") if cat_col else "0.0.0.0.0"
            parent_cat_id = map_category_to_parent(raw_cat)

            # If the raw value is a valid leaf cat_id, use it directly;
            # otherwise pick a random leaf under the resolved parent
            if raw_cat.strip() in HELP_CATEGORIES:
                leaf_cat_id = raw_cat.strip()
            else:
                leaves = CATEGORY_TREE.get(parent_cat_id, ["0.0.0.0.0"])
                leaf_cat_id = random.choice(leaves)

            requests.append({
                "req_id":         row.get(id_col, make_request_id()) if id_col else make_request_id(),
                "parent_cat_id":  parent_cat_id,
                "leaf_cat_id":    leaf_cat_id,
                "location":       row.get(loc_col, random.choice(LOCATIONS)) if loc_col else random.choice(LOCATIONS),
                "created_at":     created_at.strftime("%Y-%m-%d %H:%M:%S"),
            })

    print(f"  Loaded {len(requests):,} requests from {filepath}")
    return requests


def map_category_to_parent(raw: str) -> str:
    """Map a raw category string (from external CSV) to an official parent cat_id.
    Handles both old human-readable names and official cat_id values.
    """
    raw_stripped = raw.strip()

    # If it's already an official cat_id, derive parent directly
    if raw_stripped in HELP_CATEGORIES:
        return get_parent_cat_id(raw_stripped)

    raw_lower = raw_stripped.lower()
    mapping = {
        "food":      "1",
        "grocery":   "1",
        "meal":      "1",
        "cook":      "1",
        "clothing":  "2",
        "clothes":   "2",
        "tailor":    "2",
        "housing":   "3",
        "repair":    "3",
        "rent":      "3",
        "lease":     "3",
        "move":      "3",
        "shelter":   "3",
        "education": "4",
        "tutor":     "4",
        "career":    "4",
        "college":   "4",
        "school":    "4",
        "health":    "5",
        "medical":   "5",
        "medicine":  "5",
        "mental":    "5",
        "wellness":  "5",
        "elderly":   "6",
        "senior":    "6",
    }
    for keyword, parent_id in mapping.items():
        if keyword in raw_lower:
            return parent_id
    return "0.0.0.0.0"


# ─────────────────────────────────────────────
# BUILD INTERNAL POOL (when no external CSVs)
# ─────────────────────────────────────────────

def build_reference_pool(n_users: int, n_requests: int) -> tuple:
    """Generate internal user/request pools when external CSVs not provided."""
    users = [{"user_id": make_user_id()} for _ in range(n_users)]

    requests = []
    for _ in range(n_requests):
        parent_cat_id, leaf_cat_id = random_category()
        created_at = random_timestamp(START_DATE, END_DATE)
        requests.append({
            "req_id":        make_request_id(),
            "parent_cat_id": parent_cat_id,
            "leaf_cat_id":   leaf_cat_id,
            "location":      random.choice(LOCATIONS),
            "created_at":    created_at,
        })

    return users, requests


# ─────────────────────────────────────────────
# TABLE 1: request_comments
# ─────────────────────────────────────────────

def generate_request_comments(users: list, requests: list, n_rows: int) -> list:
    """
    Generate synthetic request_comments rows.
    comment_desc uses real Saayam category-specific language.
    """
    rows = []
    for comment_id in range(1, n_rows + 1):
        req = random.choice(requests)

        # 25% chance the commenter is the requester (follow-up)
        # 75% chance it's a volunteer (different user)
        if random.random() < 0.25:
            req_user = next((u for u in users
                             if u["user_id"] == req.get("req_user_id", "")),
                            random.choice(users))
            commenter = req_user
        else:
            commenter = random.choice(users)

        req_dt        = datetime.strptime(req["created_at"], "%Y-%m-%d %H:%M:%S")
        comment_start = req_dt
        comment_end   = min(req_dt + timedelta(days=30), END_DATE)
        created_at    = random_timestamp(comment_start, comment_end)

        created_dt   = datetime.strptime(created_at, "%Y-%m-%d %H:%M:%S")
        updated_end  = min(created_dt + timedelta(hours=72), END_DATE)
        last_updated = random_timestamp(created_dt, updated_end)

        comment_desc = pick_comment(
            req.get("parent_cat_id", "0.0.0.0.0"),
            req.get("leaf_cat_id", "0.0.0.0.0")
        )

        rows.append({
            "comment_id":      comment_id,
            "req_id":          req["req_id"],
            "commenter_id":    commenter["user_id"],
            "comment_desc":    comment_desc,
            "created_at":      created_at,
            "last_updated_at": last_updated,
            "isdeleted":       "TRUE" if random.random() < 0.05 else "FALSE",
        })

    return rows


# ─────────────────────────────────────────────
# TABLE 2: volunteer_rating
# ─────────────────────────────────────────────

def generate_volunteer_rating(users: list, requests: list, n_rows: int) -> list:
    """
    Generate synthetic volunteer_rating rows.
    Rating distribution is realistic (skewed positive).
    Feedback text matches rating sentiment.
    One unique (user_id, request_id) pair per row — no duplicates.
    """
    rows       = []
    seen_pairs = set()
    rating_id  = 1
    attempts   = 0
    max_att    = n_rows * 10

    while len(rows) < n_rows and attempts < max_att:
        attempts += 1
        req  = random.choice(requests)
        user = random.choice(users)
        pair = (user["user_id"], req["req_id"])
        if pair in seen_pairs:
            continue
        seen_pairs.add(pair)

        rating   = random.choices([1, 2, 3, 4, 5], weights=RATING_WEIGHTS, k=1)[0]
        feedback = pick_feedback(rating, req.get("parent_cat_id", "0.0.0.0.0"))

        req_dt       = datetime.strptime(req["created_at"], "%Y-%m-%d %H:%M:%S")
        rating_start = req_dt + timedelta(hours=1)
        rating_end   = min(req_dt + timedelta(days=14), END_DATE)
        if rating_start >= rating_end:
            last_update = req_dt.strftime("%Y-%m-%d %H:%M:%S")
        else:
            last_update = random_timestamp(rating_start, rating_end)

        rows.append({
            "volunteer_rating_id": rating_id,
            "user_id":             user["user_id"],
            "request_id":          req["req_id"],
            "rating":              rating,
            "feedback":            feedback,
            "last_update_date":    last_update,
        })
        rating_id += 1

    if len(rows) < n_rows:
        print(f"  Warning: only {len(rows)} unique pairs possible. "
              f"Increase pool size with --pool-size.")
    return rows


# ─────────────────────────────────────────────
# VALIDATION
# ─────────────────────────────────────────────

def validate(rows: list, table_name: str, pk_col: str):
    print(f"\n  Validation — {table_name}")
    print(f"     Rows generated : {len(rows):,}")
    pk_vals = [r[pk_col] for r in rows]
    dupes   = len(pk_vals) - len(set(pk_vals))
    nulls   = sum(1 for v in pk_vals if not v)
    print(f"     PK duplicates  : {dupes}  {'OK' if dupes == 0 else 'FAIL'}")
    print(f"     Null PKs       : {nulls}  {'OK' if nulls == 0 else 'FAIL'}")
    if table_name == "volunteer_rating":
        from collections import Counter
        dist  = Counter(r["rating"] for r in rows)
        pairs = [(r["user_id"], r["request_id"]) for r in rows]
        dp    = len(pairs) - len(set(pairs))
        print(f"     Rating dist    : {dict(sorted(dist.items()))}")
        print(f"     Dupe pairs     : {dp}  {'OK' if dp == 0 else 'FAIL'}")


# ─────────────────────────────────────────────
# CSV WRITER
# ─────────────────────────────────────────────

def write_csv(rows: list, filename: str):
    if not rows:
        return
    path = OUTPUT_DIR / filename
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)
    print(f"  Saved {filename}: {len(rows):,} rows → {path}")


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate synthetic CSVs for request_comments and volunteer_rating"
    )
    parser.add_argument("--rows",        type=int, default=100,
                        help="Rows per table (default: 100)")
    parser.add_argument("--pool-size",   type=int, default=None,
                        help="Internal pool size override")
    parser.add_argument("--seed",        type=int, default=42,
                        help="Random seed (default: 42)")
    parser.add_argument("--users-csv",   type=str, default=None,
                        help="Path to users.csv from another team (for real FK integrity)")
    parser.add_argument("--requests-csv", type=str, default=None,
                        help="Path to request.csv from another team (for real FK integrity)")
    args = parser.parse_args()

    random.seed(args.seed)
    n_rows = args.rows

    print(f"\nSaayam Synthetic Data Generator — Issue #119")
    print(f"Tables : request_comments, volunteer_rating")
    print(f"Rows   : {n_rows:,} per table")
    print(f"Seed   : {args.seed}\n")

    # ── Load users and requests ──────────────────
    ext_users    = args.users_csv    is not None
    ext_requests = args.requests_csv is not None

    if ext_users and ext_requests:
        print("Mode: EXTERNAL CSVs — using real user_ids and req_ids for full FK integrity")
        users    = load_external_users(args.users_csv)
        requests = load_external_requests(args.requests_csv)
    elif ext_users or ext_requests:
        print("Warning: provide BOTH --users-csv and --requests-csv for full FK integrity.")
        print("Falling back to internal pool for missing source.\n")
        pool = args.pool_size or max(200, n_rows * 3)
        u_int, r_int = build_reference_pool(pool, pool)
        users    = load_external_users(args.users_csv) if ext_users else u_int
        requests = load_external_requests(args.requests_csv) if ext_requests else r_int
    else:
        print("Mode: INTERNAL POOL — generating own user_ids and req_ids")
        pool = args.pool_size or max(200, n_rows * 3)
        print(f"Pool : {pool:,} users × {pool:,} requests\n")
        users, requests = build_reference_pool(pool, pool)

    # ── Generate tables ──────────────────────────
    print("Generating request_comments...")
    comments = generate_request_comments(users, requests, n_rows)
    validate(comments, "request_comments", "comment_id")
    validate_text_diversity(
        [r["comment_desc"] for r in comments], "comment_desc text"
    )
    write_csv(comments, "request_comments.csv")

    print("\nGenerating volunteer_rating...")
    ratings = generate_volunteer_rating(users, requests, n_rows)
    validate(ratings, "volunteer_rating", "volunteer_rating_id")
    validate_text_diversity(
        [r["feedback"] for r in ratings], "feedback text"
    )
    write_csv(ratings, "volunteer_rating.csv")

    print(f"\nDone. Output: {OUTPUT_DIR}/")
    print(f"  request_comments.csv  — {len(comments):,} rows")
    print(f"  volunteer_rating.csv  — {len(ratings):,} rows")
    print(f"\nOnce users.csv and request.csv are ready from the other team, run:")
    print(f"  python generate_119.py --users-csv database/mock_db/users.csv \\")
    print(f"                         --requests-csv database/mock_db/request.csv")
    print(f"  This regenerates both files with real FK consistency.\n")


if __name__ == "__main__":
    main()